# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c44b0b034891aaa7d7c7bbac902343c10670bd0b57bfb8581010c633b447cb361401e53ffa60b6d141f5c63f3a7296dd2a28dc188a78e2bd78d3de8a594ce81

test:
  secret_key_base: 9bb8f86360ce21ac7daddea11dc3a22ebe949cc6be48bc632b82649a3003e01017a4d2d49b8c384eb9d978b5bb0767d8edd4bf2262eccb6a0cc729a21132040a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
